### ISSUE TITLE
Add InheritedAccessRightsMask column to the info

### ISSUE THREAD

**Issue by pmalecka** [ameed/Ameed.XTBPlugins#1]
The results grid could also contain the  InheritedAccessRightsMask column - since this is available in the POA table and is important for implicit shares.

**Comment by ameed** [comment]
Good point, will add in next version.
Thanks

**Comment by ameed** [comment]
Added with most recent version: 1.2017.5.16, please install from plugin store. Added a description of integer mask value, and on hide / show owner-share details, grid will show the actual integer mask.
