### ISSUE TITLE
Hyperlinks from row back to CRM

### ISSUE THREAD

**Issue by mscottsewell** [ameed/Ameed.XTBPlugins#3]
As a suggestion, in the table of records returned, enable a hyperlink from each row back to the corresponding record in Dynamics 365. - This would avoid some confusion if the names of the records were not sufficiently unique for the user to find the record.

**Comment by ameed** [comment]
Thanks for suggestion Scott ... that is one of the top ones for next version features ... just have to squeeze some time out of busy routine with customer deliverables 😊

**Comment by ameed** [comment]
Hi Scott, this feature is now available in most recent version: 1.2018.12.28
Sorry for such a long wait ... though I hope you find it useful ... thank you for support :)
